<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iluwatar</groupId>
        <artifactId>java-design-patterns</artifactId>
        <version>1.26.0-SNAPSHOT</version>
    </parent>
    <artifactId>functional-modern-patterns</artifactId>
    <packaging>pom</packaging>
    <name>functional-modern-patterns Maven Webapp</name>
    <url>http://maven.apache.org</url>

    <modules>
        <module>collection-pipeline</module>
        <module>combinator</module>
        <module>currying</module>
        <module>function-composition</module>
        <module>monad</module>
        <module>pipeline</module>
        <module>tolerant-reader</module>
        <module>trampoline</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <finalName>functional-modern-patterns</finalName>
    </build>
</project>
