<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.iluwatar</groupId>
        <artifactId>java-design-patterns</artifactId>
        <version>1.26.0-SNAPSHOT</version>
    </parent>
    <artifactId>concurrency-async-patterns</artifactId>
    <packaging>pom</packaging>
    <name>concurrency-async-patterns Maven Webapp</name>
    <url>http://maven.apache.org</url>

    <modules>
        <module>active-object</module>
        <module>async-method-invocation</module>
        <module>balking</module>
        <module>event-based-asynchronous</module>
        <module>event-driven-architecture</module>
        <module>event-queue</module>
        <module>guarded-suspension</module>
        <module>half-sync-half-async</module>
        <module>leader-followers</module>
        <module>map-reduce</module>
        <module>monitor</module>
        <module>producer-consumer</module>
        <module>promise</module>
        <module>reactor</module>
    </modules>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <build>
        <finalName>concurrency-async-patterns</finalName>
    </build>
</project>
